[package]
name = "nas_rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["gui"]

[dependencies]
clap = "4.5.34"
openssl = "0.10.71"
rkyv = { version = "0.8.10" }
serde = { version = "1.0.219", features = ["derive"] }
