[package]
name = "gui"
version = "0.1.0"
edition = "2024"

[dependencies]
nas_rs = { path = ".." }
iced = "0.13.1"
openssl = { version = "0.10.70", features = ["vendored"] }
rancor = "0.1.0"
open = "5.3.2"
rfd = "0.15.3"
iced_aw = { version = "0.12.2", features = ["number_input"] }
